import math

x = float(input("Input the number for x: "))
y = float(input("Input the number for y: "))
pi = math.pi
e = math.e
inf = math.inf
ninf = -math.inf
nan = math.nan
ceil_x = math.ceil(x)
floor_x = math.floor(x)
trunc_x = math.trunc(x)
copysign_xy = math.copysign(x, y)
fabs_x = math.fabs(x)
fmod_xy = math.fmod(x, y)
factorial_x = math.factorial(int(x))  
power_xy = math.pow(x, y)
sqrt_x = math.sqrt(x)
exp_x = math.exp(x)
log_x = math.log(x)
log10_x = math.log10(x)
log2_x = math.log2(x)
sin_x = math.sin(x)
cos_x = math.cos(x)
tan_x = math.tan(x)
asin_x = math.asin(x)
acos_x = math.acos(x)
atan_x = math.atan(x)
atan2_yx = math.atan2(y, x)
sinh_x = math.sinh(x)
cosh_x = math.cosh(x)
tanh_x = math.tanh(x)
asinh_x = math.asinh(x)
acosh_x = math.acosh(x)
atanh_x = math.atanh(x)
degrees_x = math.degrees(x)
radians_x = math.radians(x)
erf_x = math.erf(x)
erfc_x = math.erfc(x)
gamma_x = math.gamma(x)
lgamma_x = math.lgamma(x)
isfinite_x = math.isfinite(x)
isinf_x = math.isinf(x)
isnan_x = math.isnan(x)
isclose_xy = math.isclose(x, y, abs_tol=10)
frexp_x = math.frexp(x)
print(f"x: {x}")
print(f"y: {y}")
print(f"Pi: {pi}")
print(f"Euler's number (e): {e}")
print(f"Positive Infinity: {inf}")
print(f"Negative Infinity: {ninf}")
print(f"Not a Number (NaN): {nan}")
print(f"Ceiling of x: {ceil_x}")
print(f"Floor of x: {floor_x}")
print(f"Truncated value of x: {trunc_x}")
print(f"x with the sign of y: {copysign_xy}")
print(f"Absolute value of x: {fabs_x}")
print(f"Remainder of x / y: {fmod_xy}")
print(f"Factorial of x: {factorial_x}")
print(f"x raised to the power y: {power_xy}")
print(f"Square root of x: {sqrt_x}")
print(f"e raised to the power x: {exp_x}")
print(f"Natural logarithm of x: {log_x}")
print(f"Base-10 logarithm of x: {log10_x}")
print(f"Base-2 logarithm of x: {log2_x}")
print(f"Sine of x: {sin_x}")
print(f"Cosine of x: {cos_x}")
print(f"Tangent of x: {tan_x}")
print(f"Arcsine of x: {asin_x}")
print(f"Arccosine of x: {acos_x}")
print(f"Arctangent of x: {atan_x}")
print(f"Arctangent of y / x: {atan2_yx}")
print(f"Hyperbolic sine of x: {sinh_x}")
print(f"Hyperbolic cosine of x: {cosh_x}")
print(f"Hyperbolic tangent of x: {tanh_x}")
print(f"Inverse hyperbolic sine of x: {asinh_x}")
print(f"Inverse hyperbolic cosine of x: {acosh_x}")
print(f"Inverse hyperbolic tangent of x: {atanh_x}")
print(f"x in degrees: {degrees_x}")
print(f"x in radians: {radians_x}")
print(f"Error function of x: {erf_x}")
print(f"Complementary error function of x: {erfc_x}")
print(f"Gamma function of x: {gamma_x}")
print(f"Natural logarithm of the absolute value of the gamma function of x: {lgamma_x}")
print(f"x is finite: {isfinite_x}")
print(f"x is positive or negative infinity: {isinf_x}")
print(f"x is NaN: {isnan_x}")
print(f"Is x close to y: {isclose_xy}")
print(f"Mantissa and exponent of x: {frexp_x}")

